# Generated by Django 4.2.11 on 2024-05-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('beauty_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.TextField()),
                ('add_time', models.DateTimeField()),
                ('winter_level', models.CharField(max_length=10)),
                ('summer_level', models.CharField(max_length=10)),
                ('autumn_level', models.CharField(max_length=10)),
                ('spring_level', models.CharField(max_length=10)),
                ('coord_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.CharField(default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fam', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otc', models.CharField(max_length=100)),
            ],
        ),
    ]
