# Generated by Django 4.2.11 on 2024-05-12 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('other_titles', models.CharField(max_length=100)),
                ('connect', models.TextField()),
                ('add_time', models.DateTimeField()),
                ('winter_level', models.CharField(max_length=10)),
                ('summer_level', models.CharField(max_length=10)),
                ('autumn_level', models.CharField(max_length=10)),
                ('spring_level', models.CharField(max_length=10)),
                ('status', models.CharField(default='new', max_length=20)),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fam', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('otc', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('pereval_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mountain_passes.perevaladded')),
            ],
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_passes.users'),
        ),
    ]
