# Generated by Django 4.2.11 on 2024-05-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountain_passes.coord'),
        ),
    ]
