# Generated by Django 4.2.11 on 2024-05-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountain_passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perevaladded',
            table=None,
        ),
    ]
